Initial create page
PlaylistCrafters/CS375Spotify pull request #20
Opened 2023-08-13 23:53 UTC by mattprotacio

2023-08-14 00:29 UTC, ll886 requested changes
I'm thinking we can point this branch to the one I created: https://github.com/PlaylistCrafters/CS375Spotify/compare/main...generate-game

I created a /api/rooms endpoint to create the game rooms. It should store the game rules that are defined here. so we can update `handleSubmit` to make a POSTto this endpoint, if successful, redirect the user to /rooms/<room id returned by the POST>. 

We can also update the console.log() to log the whole request instead of just `explicit`

2023-08-15 02:50 UTC, ll886 commented
Could do something like this. https://nextjs.org/docs/pages/building-your-application/data-fetching/building-forms#part-6-form-submission-with-javascript-enabled and

2023-08-20 19:25 UTC, ll886 requested changes

2023-08-20 19:25 UTC, devappslabs commented on frontend/src/app/create/page.js
> +   let gameRules = [snippetLength, rounds, explicit, powerups];
let's send it as an object so it's easier to read in the backend

```
{
    "snippetLength": snippetLength,
    "rounds": rounds,
    "allowExplicit": allowExplicit
}
```

(excluding powerups for now until we figure out what power ups and how to create/handle them

2023-08-20 19:25 UTC, devappslabs commented on frontend/package-lock.json
>  {
what is being changed in this file?

2023-08-20 19:25 UTC, devappslabs commented on frontend/src/app/create/page.js
> +            <div id="pageContainer">
We can build a form like this to avoid having to use the `document` object: https://nextjs.org/docs/pages/building-your-application/data-fetching/building-forms#part-6-form-submission-with-javascript-enabled

2023-08-20 19:25 UTC, devappslabs commented on frontend/src/app/create/page.js
> +        let gameRules = [snippetLength, rounds, explicit, powerups];
gameRules should be an object like this

```
{
    "snippetLength": snippetLength,
    "rounds": rounds,
    "allowExplicit": allowExplicit
}
```

// want to call it snippetLength since it's not initially clear what "s" stands for
// want to call it "allowExplicit" to make it clear it's not a game of only explicit songs vs no explicit songs
// also not considering powerups yet

2023-08-20 19:25 UTC, devappslabs commented on frontend/src/app/create/page.js
> +            document.getElementById("message").textcontent = "unable to create room";
We can avoid using document.getElementById to manually update the dom by doing something like this: https://nextjs.org/learn/foundations/from-javascript-to-react/adding-interactivity-with-state

```
const [errorMessage, setErrorMessage] = React.useState("");
```

and then if the response status is not a 200

```
setErrorMessage("Invalid room code");
```

and when rendering 
```
<div>{errorMessage}</div>
```

2023-08-20 19:25 UTC, devappslabs commented on frontend/src/app/create/page.js
> +        const endpoint = '/api/rooms';
This route will not work because the backend will be deployed on a different host and port:

Branch of `generate-game` and do something like 

![image](https://github.com/PlaylistCrafters/CS375Spotify/assets/59991196/3b337bbb-def7-4cf2-ad7c-dc7d8e060c96)

2023-08-21 15:06 UTC, ll886 commented
wait until https://github.com/PlaylistCrafters/CS375Spotify/pull/26 is merged

2023-08-21 15:06 UTC, devappslabs requested changes
wait until https://github.com/PlaylistCrafters/CS375Spotify/pull/26 is merged

2023-08-21 16:31 UTC, ll886 requested changes, later dismissed

2023-08-21 16:31 UTC, ll886 commented on frontend/src/app/create/page.js
> +        let gameRules = {"snippetLengt": event.target.sLength.value,
"snippetLength"

2023-08-21 16:31 UTC, ll886 commented on frontend/src/app/create/page.js
> +            let id = response.json();
We should do something like

```
response.json().then((body) => {
    router.push(`/rooms/${body.roomId}`)
});
```

2023-08-22 18:33 UTC, brandonkhop approved these changes

2023-08-22 18:33 UTC, merged