Initial join page, needs fetch requests implemented
PlaylistCrafters/CS375Spotify pull request #21
Opened 2023-08-13 23:53 UTC by mattprotacio

2023-08-14 01:09 UTC, ll886 requested changes
in my branch: https://github.com/PlaylistCrafters/CS375Spotify/compare/spotify-functions...generate-game

I created an endpoint.

Send a GET request to `/api/rooms?roomId=<code value>` to check if the room exists. If it doesn't, you'll get a 400. If it does exist, you'll receive a 200

2023-08-20 19:24 UTC, ll886 requested changes

2023-08-20 19:24 UTC, devappslabs commented on frontend/src/app/join/page.js
> +
Since we're using a frontend framework, we should be able to avoid needing to use `document.getElementById`. 

See https://github.com/PlaylistCrafters/CS375Spotify/pull/25/files for an example:

2023-08-20 19:24 UTC, devappslabs commented on frontend/src/app/join/page.js
> +
optional for now though. we can merge this version if we want to test sooner than later but it'd probably good to refactor later

2023-08-20 19:24 UTC, devappslabs commented on frontend/src/app/join/page.js
> +
Something like https://nextjs.org/docs/pages/building-your-application/data-fetching/building-forms#part-6-form-submission-with-javascript-enabled

2023-08-20 19:24 UTC, devappslabs commented on frontend/src/app/join/page.js
> +            document.getElementById("message").textContent = "Invalid Room";
We can avoid using document.getElementById to manually update the dom by doing something like this: https://nextjs.org/learn/foundations/from-javascript-to-react/adding-interactivity-with-state

```
const [errorMessage, setErrorMessage] = React.useState("");
```

and then if the response status is not a 200

```
setErrorMessage("Invalid room code");
```

and when rendering 
```
<div>{errorMessage}</div>
```

2023-08-20 19:24 UTC, devappslabs commented on frontend/src/app/join/page.js
> +        let code = document.getElementById("code").value;
We can avoid using `document.getElementById` by doing something like this: https://nextjs.org/docs/pages/building-your-application/data-fetching/building-forms#part-6-form-submission-with-javascript-enabled with a form to take in the code

2023-08-20 19:24 UTC, devappslabs commented on frontend/src/app/join/page.js
> +        const endpoint = `/rooms/${code}`;
This route will not work because the backend will be deployed on a different host and port:

Branch of `generate-game` and do something like 

![image](https://github.com/PlaylistCrafters/CS375Spotify/assets/59991196/3b337bbb-def7-4cf2-ad7c-dc7d8e060c96)

and endpoint is `/api/rooms/<code>`

2023-08-21 16:24 UTC, ll886 submitted a review, later dismissed

2023-08-21 16:24 UTC, ll886 commented on frontend/src/app/join/page.js
> +        let code = event.target.code;
need to do `event.target.code.value`

2023-08-22 18:37 UTC, brandonkhop approved these changes

2023-08-22 18:37 UTC, merged